name: Build and Deploy
permissions:
  contents: write
on:
  push:
    branches:
      - main
    paths:
      - presention/**
jobs:
  build-and-deploy-gh-page:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
    - name: Build
      shell: bash
      run: |
        npm i -g pnpm
        pnpm install
        pnpm run-script build-gh
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist